packages:
  - "ui/**"
  - "packages/**"

# https://pnpm.io/catalogs
catalog:
  unocss: 66.1.0-beta.2
  "@arethetypeswrong/cli": 0.17.4
  turbo: 2.4.4
  typescript: 5.7.3
  "@types/node": 22.13.5

catalogs:
  nextjs:
    next: 15.1.7
    eslint-config-next: 15.1.7
  eslint-flat:
    eslint: 9.21.0
    globals: 16.0.0
    "@eslint/js": 9.21.0
    typescript-eslint: 8.25.0
    prettier: 3.5.2
    prettier-plugin-tailwindcss: 0.6.11
    eslint-config-prettier: 10.0.1
    eslint-plugin-react: 7.37.4
    eslint-plugin-react-hooks: 5.1.0
    eslint-plugin-tailwindcss: 3.18.0
    "@eslint/eslintrc": 3.3.0
  tailwind:
    tailwindcss: 4.0.9
    postcss: 8.5.3
  nestjs:
    "@nestjs/common": 11.0.10
    "@nestjs/core": 11.0.10
    "@nestjs/platform-express": 11.0.10
    "reflect-metadata": 0.2.2
    "@nestjs/cli": 11.0.5
    "@nestjs/schematics": 11.0.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.10
    "@types/react-dom": 19.0.4
